### ISSUE TITLE
Add capability to flip signals on whatever EDF you are viewing

### ISSUE THREAD

**Issue by mrueschman** [nsrr/altamira#2]
At times signals are inverted in the EDF and need to be flipped to get the correct orientation. You may want to flip individual signals on a case-by-case basis. Perhaps this could be done by simply clicking on the signal name in the lefthand pane.

**Comment by remomueller** [comment]
Alternatively, I could check which signals have their physical dimensions swapped, (negative gain), and simply flip those. Do you have any specific signals for reference?

**Comment by remomueller** [comment]
Looks like it's already doing part of this when the signals are scaled. However, it doesn't flip the signal correctly when autoscaling is off.
